### ISSUE TITLE
MSE is not stable, and jumb much 

### ISSUE THREAD

**Issue by DeepKnowledge1** [YeongHyeon/MemAE#1]
see these samples, 
the MSE in the new epoch is very large than the old one, 
I thought this might be the Learning rate, but the lr is 1e-4

Do you have an idea how to handle this problem? 

Epoch [2281 / 10000] (59332 iteration)  MSE:383912.281, W-ETRP:0.003, Total:7678.246

Epoch [2285 / 10000] (59436 iteration)  MSE:198418.922, W-ETRP:0.003, Total:3968.378

Epoch [2308 / 10000] (60034 iteration)  MSE:327438.281, W-ETRP:0.003, Total:6548.765

Epoch [2313 / 10000] (60164 iteration)  MSE:308482.469, W-ETRP:0.003, Total:6169.649

[2315 / 10000] (60216 iteration)  MSE:152412.391, W-ETRP:0.003, Total:3048.248

**Comment by YeongHyeon** [comment]
I'll check this repository follow your comment.
In the checking duration, I refer you to use the following alternative source code.
https://github.com/YeongHyeon/MemAE-TF2

Thank you for your comment. 
:)
